// Source: https://github.com/ugurkocde/kql_search_submissions
// Collected: 2026-07-21
// KQL Library - https://github.com/sivolko/kql-library

AuditLogs
| where OperationName == "Delete user"
// Exclude Accounts deleted via AD Sync, add more exclusions depending on your environment
// | where InitiatedBy.user.id != ""
// Trim ID from user
| extend DeletedUser = substring(TargetResources[0].userPrincipalName, 32)
| extend DeletedBy = InitiatedBy.user.userPrincipalName