// Source: https://github.com/kkroth0/threat-hunting-ptbr
// Collected: 2026-07-26
// KQL Library - https://github.com/sivolko/kql-library

let lookback = 14d;
let huntTerms = dynamic(["T1082", "gootloader", "powershell", "systeminfo", "H055", "PowerShell", "Get-CimInstance", "cmdlet", "query", "Win32_OperatingSystem", "ConvertTo-Csv", "extract", "MainWindowTitle", "properties", "running", "processes", "exfiltrating", "environment", "variables", "under", "characters", "desktop", "cmd.exe", "wscript", "cscript", "mshta", "rundll32", "regsvr32", "CurrentVersion\\Run", "Scheduled", "Service", "Registry"]);
union withsource=SourceTable isfuzzy=true
    SecurityEvent,
    WindowsEvent,
    TrendMicro_XDR_OAT_CL,
    TrendMicro_XDR_WORKBENCH_CL
| where TimeGenerated >= ago(lookback)
| extend SearchBlob = tostring(pack_all())
| where SearchBlob has_any (huntTerms)
| extend HuntId = "H055", SourceUrl = "https://github.com/THORCollective/HEARTH/blob/main/Flames/H055.md"
| project TimeGenerated, HuntId, SourceTable, SourceUrl, SearchBlob
| order by TimeGenerated desc