// Source: https://github.com/Gyarbij/Artemis
// Collected: 2026-07-23
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where ActionType == "TamperingAttempt"
| extend OriginalRegistryValue = tostring(AdditionalFields.OriginalValue)
| extend Status = tostring(AdditionalFields.Status)
| extend TamperingAction = tostring(AdditionalFields.TamperingAction)
| extend AttemptedRegistryValue = tostring(AdditionalFields.TamperingAttemptedValue)
| extend TargetRegistryKey = tostring(AdditionalFields.Target)
| where TamperingAction == "RegistryModification"
| project
    TimeGenerated,
    DeviceName,
    TamperingAction,
    Status,
    OriginalRegistryValue,
    AttemptedRegistryValue,
    TargetRegistryKey,
    InitiatingProcessAccountName,
    InitiatingProcessCommandLine