// Source: https://github.com/frances-saunders/cybersecurity-portfolio
// Collected: 2026-07-20
// KQL Library - https://github.com/sivolko/kql-library

AzureActivity
| where OperationNameValue in ("Microsoft.Network/publicIPAddresses/write", "Microsoft.Network/virtualNetworkGateways/write")
| extend ResourceId = tostring(parse_json(Properties).resourceId)
| join kind=leftanti (
    ResourceContainers
    | where type =~ "microsoft.network/privateendpoints"
    | project PrivateEndpointId = id
) on $left.ResourceId == $right.PrivateEndpointId
| project TimeGenerated, ResourceId, Caller, ActivityStatusValue