// Source: https://github.com/DancinDinoo/KQL
// Collected: 2026-07-22
// KQL Library - https://github.com/sivolko/kql-library

let recipientthreshold = ; // Adjust based on risk tolerance
let tenantallowlist = pack_array(""); // Trusted third parties
OfficeActivity
| where TimeGenerated > ago(3h)
| where RecordType == "MicrosoftTeams"
| where Operation == "ChatCreated"
| where CommunicationType == "OneOnOne"
| extend SenderUPN = UserId | extend SenderDisplayName = tostring(Members.[0].DisplayName) | extend tostring(SenderTenantID = Members[0].OrganizationId)
| extend RecipientUPN = Members.[1].UPN | extend RecipientName = tostring(Members.[1].DisplayName) | extend tostring(RecipientTenantID = Members[1].OrganizationId)
| summarize Recipients = make_list(RecipientUPN), FirstEmailSeen = min(TimeGenerated), LatestEmailSeen = max(TimeGenerated), NumberofRecipients = count() by SenderUPN, SenderDisplayName, SenderTenantID
| where Recipients != "[]" // Blank fields with Recipient/Sender Info is very likely to be due to Graph emails, its a limitation of this log source
| where SenderTenantID !in (tenantallowlist)
| where NumberofRecipients >= recipientthreshold

// I've recreated this in CloudAppEvents as well, so you've got the option of both depending on what your log capabilities are :)
// https://github.com/DancinDinoo/Sentinel-Microsoft-Rules/blob/main/CloudAppEvents/Teams%20message%20spray.kql