// Source: https://github.com/javierDAW/detection-diary
// Collected: 2026-07-17
// KQL Library - https://github.com/sivolko/kql-library

DeviceProcessEvents
| where Timestamp >= ago(30d)
| where (FileName =~ "rubeus.exe"
         or ProcessCommandLine has_any (" asktgt ", " s4u ", " s4u2self ", " kerberoast ", " /impersonateuser:"))
   and ProcessCommandLine has_any ("/ticket:","/user:","/service:","/msdsspn:")
| project Timestamp, DeviceName, AccountName, FileName, FolderPath, ProcessCommandLine, InitiatingProcessFileName
| join kind=leftouter (
    SecurityEvent
    | where EventID == 4769 and TicketEncryptionType in ("0x12","0x17") // AES256, RC4
    | summarize TGSCount=count() by Account, bin(TimeGenerated,5m), Computer
    | where TGSCount > 50
    | project TimeGenerated, Account, Computer, TGSCount
  ) on $left.AccountName == $right.Account
| summarize hits = count()