// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-10-01
// KQL Library - https://github.com/sivolko/kql-library

AuditLogs
| where OperationName == "Read BitLocker key"
| extend Actor = tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)
| extend s = tostring(AdditionalDetails[0].value)
| parse s with * "ID: '" KeyId "'" *
| parse s with * "device: '" DeviceId "'"
| project TimeGenerated, OperationName, Actor, KeyId, DeviceId