// Source: https://github.com/sivolko/kql-library
// Collected: 2026-05-15
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| project TimeGenerated, EventID, TargetAccount, SubjectAccount, UserAccountControl
| where EventID == "4738"
| where UserAccountControl has ("2082")
| extend Activity = strcat("Account set to password not required")
| project TimeGenerated, Target=TargetAccount, Actor=SubjectAccount, Activity