// Source: https://github.com/agent4t2/microsoft-sentinel
// Collected: 2026-07-18
// KQL Library - https://github.com/sivolko/kql-library

let timerange=7d;
SecurityEvent
| where TimeGenerated > ago(timerange)
//| where Computer startswith "GTM" // Uncomment to specify host group. 
| summarize CountPerGroup = count() by EventID
| extend TotalCount = toscalar(Syslog | where TimeGenerated > ago(timerange) | summarize count())
| extend Percentage = round((CountPerGroup * 100.0) / TotalCount, 2)
| order by Percentage desc