// Source: https://github.com/troytrojan01/ot-cybersecurity-with-sentinel
// Collected: 2026-07-14
// KQL Library - https://github.com/sivolko/kql-library

CommonSecurityLog
| where DeviceVendor =~ "Forescout" and DeviceProduct =~ "eyeSegment"
| extend
    SrcZone      = DeviceCustomString1,
    DstZone      = DeviceCustomString2,
    PolicyName   = DeviceCustomString3,
    Action       = DeviceCustomString4,         // Alert, Block, Audit
    Severity     = toint(LogSeverity)
| project
    TimeGenerated,
    RuleId       = DeviceEventClassID,
    Activity,
    Severity,
    SrcZone,
    DstZone,
    PolicyName,
    Action,
    SourceIP,
    SourcePort,
    DestinationIP,
    DestinationPort,
    Protocol,
    EventId      = ExternalID,
    Message