// Source: https://github.com/ep3p/Sentinel_KQL
// Collected: 2026-05-20
// KQL Library - https://github.com/sivolko/kql-library

OfficeActivity
| where TimeGenerated between (ago(90d) .. now())
| where isnotempty(ClientIP)
| extend
    IsPrivateRange = isnotempty(parse_ipv4(ClientIP)) and ipv4_is_private(ClientIP),
    IsTenSixtyRange = isnotempty(parse_ipv4(ClientIP)) and ipv4_is_in_any_range(ClientIP, "10.60.0.0/16")
| where IsPrivateRange
| summarize log(count()) by bin(TimeGenerated, 1d), OfficeWorkload
| render columnchart