// Source: https://github.com/DancinDinoo/KQL
// Collected: 2026-06-25
// KQL Library - https://github.com/sivolko/kql-library

  SecurityEvent
  | where EventID == "7040"
  | extend ParsedParameters = parse_xml(EventData)
  | extend RegistryValue = tostring(parse_json(tostring(parse_json(tostring(ParsedParameters.EventData)).Data))[0].["#text"])
  | extend NewParameterState = tostring(parse_json(tostring(parse_json(tostring(ParsedParameters.EventData)).Data))[2].["#text"])
  | extend CurrentParameterState = tostring(parse_json(tostring(parse_json(tostring(ParsedParameters.EventData)).Data))[1].["#text"])
  | where RegistryValue == "Remote Registry" and CurrentParameterState == "disabled" and NewParameterState == "demand start"
  | project-rename RemoteRegistryEnabledTime = TimeGenerated
  | join kind=inner (
  SecurityEvent
  | where EventID == "7040"
  | extend ParsedParameters = parse_xml(EventData)
  | extend RegistryValue = tostring(parse_json(tostring(parse_json(tostring(ParsedParameters.EventData)).Data))[0].["#text"])
  | extend NewParameterState = tostring(parse_json(tostring(parse_json(tostring(ParsedParameters.EventData)).Data))[2].["#text"])
  | extend CurrentParameterState = tostring(parse_json(tostring(parse_json(tostring(ParsedParameters.EventData)).Data))[1].["#text"])
  | where RegistryValue == "Remote Registry" and CurrentParameterState == "demand start" and NewParameterState == "disabled"
  | project-rename RemoteRegistryDisabledTime = TimeGenerated 
  ) on Computer
  | extend TimeBetween = RemoteRegistryDisabledTime - RemoteRegistryEnabledTime
  | where TimeBetween between (0s .. 10s)
  | project RemoteRegistryEnabledTime, RemoteRegistryDisabledTime, Computer, SystemUserId, RegistryValue, ParsedParameters

  // Identifies known indicators of Secretsdump.py after execution
  // https://github.com/un33k/impacket/blob/master/examples/secretsdump.py 
  // https://github.com/fortra/impacket/tree/master