// Source: https://github.com/sivolko/kql-library
// Collected: 2026-07-20
// KQL Library - https://github.com/sivolko/kql-library

let targetdevice = "device";
let SearchWindow = 48h; //Customizable h = hours, d = days
DeviceEvents
| where Timestamp > ago(SearchWindow)
| where DeviceName == targetdevice
| where ActionType startswith "ASR"
| project
     Timestamp,
     ActionType,
     FileName,
     FolderPath,
     ProcessCommandLine,
     InitiatingProcessCommandLine,
     AccountDomain,
     AccountName