// Source: https://github.com/le0li9ht/Microsoft-Sentinel-Queries
// Collected: 2026-05-25
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent 
| where EventID==4624 
| where AuthenticationPackageName contains "WDigest" 
| summarize count() by Computer 

//AT DC - Identify WDigest authentication requests
SecurityEvent 
| where EventID==4776 
| where AuthenticationPackageName contains "WDigest" 

//Identify Wdigest Authentication Downgrade attack: 
SecurityEvent 
| where EventID==4657 
//Modified HKEY_LOCAL_MACHINESystemCurrentControlSetControlSecurityProvidersWDigestUseLogonCredential to 1
| where ObjectName contains "WDigest" and ObjectValueName contains "UseLogonCredential" and NewValue==1