// Source: https://github.com/reversinglabs/reversinglabs-siem-rules
// Collected: 2026-05-23
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where EventID == 4657
| parse ObjectName with "\\REGISTRY\\" RegistryKey
| where RegistryKey matches regex @"USER\\.*\\Control Panel\\Desktop"
| where ObjectName == "Wallpaper"
| where NewValue has "dlaksjdoiwq.jpg"
| project TimeGenerated, Computer, RegistryKey, NewValue, OldValue, ProcessName, Account, Type
| union (DeviceRegistryEvents
| where ActionType == "RegistryValueSet"
| where RegistryKey matches regex @"HKEY_CURRENT_USER\\.*\\Control Panel\\Desktop"
| where RegistryValueName == "Wallpaper"
| where RegistryValueData has "dlaksjdoiwq.jpg"
| project TimeGenerated=Timestamp, DeviceId, DeviceName, RegistryKey, NewRegistryValueData=RegistryValueData, InitiatingProcessAccountName, InitiatingProcessCommandLine, InitiatingProcessId, InitiatingProcessParentFileName, Type)