// Source: https://github.com/Crimson7research/C7SigmaTools
// Collected: 2026-05-19
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where Data contains "HostApplication=" and (not(((Data contains "HostApplication=" and Data contains ":/Windows/System32/WindowsPowerShell/v1.0/powershell") or (Data contains "HostApplication=" and Data contains ":/Windows/SysWOW64/WindowsPowerShell/v1.0/powershell") or (Data contains "HostApplication=" and Data contains ":\\Windows\\System32\\sdiagnhost.exe") or (Data contains "HostApplication=" and Data contains ":\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell") or (Data contains "HostApplication=" and Data contains ":\\Windows\\SysWOW64\\sdiagnhost.exe") or (Data contains "HostApplication=" and Data contains ":\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell") or Data contains "HostApplication=powershell"))) and (not(Data contains "Citrix\\ConfigSync\\ConfigSync.ps1"))