// Source: https://github.com/sivolko/kql-library
// Collected: 2026-06-25
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where EventID == 4688
| where Process == "rundll32.exe" and CommandLine matches regex @"C:\\Users\\.*\\AppData\\Roaming\\Microsoft\\Templates\\.*\.(dat|dll)"
| union isfuzzy=true
((DeviceProcessEvents
| where FileName == "rundll32.exe" and ProcessCommandLine matches regex @"C:\\Users\\.*\\AppData\\Roaming\\Microsoft\\Templates\\.*\.(dat|dll)"
),
(SysmonParser
| where EventID == 1
| where Image == "rundll32.exe" and CommandLine matches regex @"C:\\Users\\.*\\AppData\\Roaming\\Microsoft\\Templates\\.*\.(dat|dll))
)