// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-05-20
// KQL Library - https://github.com/sivolko/kql-library

let knownapps=
    OfficeActivity
    | where TimeGenerated > ago(180d) and TimeGenerated < ago(7d)
    | where OfficeWorkload == "MicrosoftTeams"
    | where Operation == "AppInstalled"
    | distinct AzureADAppId;
OfficeActivity
| where TimeGenerated > ago (7d)
| where OfficeWorkload == "MicrosoftTeams"
| where Operation == "AppInstalled"
| where AzureADAppId !in (knownapps)
| project TimeGenerated, UserId, AddonName, AzureADAppId