// Source: https://github.com/sivolko/kql-library
// Collected: 2026-06-28
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where ActionType == "UsbDriveMounted" or ActionType == "UsbDriveUnmounted"
| extend parsed = parse_json(AdditionalFields)
| project 
    Timestamp,
    DeviceName,
    DeviceId,
    ActionType,
    DriveLetter = tostring(parsed.DriveLetter),
    Manufacturer = tostring(parsed.Manufacturer),
    ProductName = tostring(parsed.ProductName),
    SerialNumber = tostring(parsed.SerialNumber),
    Volume = tostring(parsed.Volume)
| sort by Timestamp desc