// Source: https://github.com/Azure/ausgovcaf-cloudsoe
// Collected: 2026-06-02
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent 
| where EventID == 4650 or EventID == 4651
| extend ed = parse_xml(EventData).EventData.Data
| mv-apply ed on 
(
    where ed['@Name'] == 'DHGroup'
    | project DHGroup = ed['#text']
)
| where DHGroup != "%%8232" and DHGroup != "%%8248" and DHGroup != "%%8233" and DHGroup != "%%8234"
| project TimeGenerated, Computer, Activity, DHGroup