// Source: https://github.com/BrianTJackett/log-analytics-samples
// Collected: 2026-05-28
// KQL Library - https://github.com/sivolko/kql-library

let SiteUrl = dynamic(['<siteUrl>']);
let StartDate = ago(7d);
let OperationsToMonitor = dynamic(['AccessInvitationAccepted',
                                    'AccessInvitationCreated',
                                    'AccessInvitationExpired',
                                    'AccessInvitationRevoked',
                                    'AccessInvitationUpdated',
                                    'SharedLinkCreated',
                                    'SharedLinkDisabled',
                                    'SharingInvitationAccepted',
                                    'SharingRevoked',
                                    'SharingSet']);
OfficeActivity
| where TimeGenerated > StartDate
| where Site_Url in~ (SiteUrl)
| where Operation in (OperationsToMonitor)