// Source: https://github.com/obsida-uk/Azure-BlueTeam-Toolkit
// Collected: 2026-06-12
// KQL Library - https://github.com/sivolko/kql-library

let signins=
SigninLogs
| where TimeGenerated > ago (90d)
| where AppDisplayName has "Application Name"
| project TimeGenerated, UserPrincipalName, AppDisplayName;
IdentityInfo
| where TimeGenerated > ago (21d)
| summarize arg_max(TimeGenerated, *) by AccountUPN
| extend UserPrincipalName = AccountUPN
| where GroupMembership contains "Group that gives access to Application"
| join kind=leftanti signins on UserPrincipalName
| project UserPrincipalName