// Source: https://github.com/Jiayang-Lai/100-Days-of-KQL
// Collected: 2026-05-28
// KQL Library - https://github.com/sivolko/kql-library

let DemoDeviceEvents = externaldata(
    AccountDomain:string,
    AccountName:string,
    AccountSid:string,
    ActionType:string,
    AdditionalFields:dynamic,
    AppGuardContainerId:string,
    DeviceId:string,
    DeviceName:string,
    FileName:string,
    FileOriginIP:string,
    FileOriginUrl:string,
    FolderPath:string,
    InitiatingProcessAccountDomain:string,
    InitiatingProcessAccountName:string,
    InitiatingProcessAccountObjectId:string,
    InitiatingProcessAccountSid:string,
    InitiatingProcessAccountUpn:string,
    InitiatingProcessCommandLine:string,
    InitiatingProcessFileName:string,
    InitiatingProcessFolderPath:string,
    InitiatingProcessId:long,
    InitiatingProcessLogonId:long,
    InitiatingProcessMD5:string,
    InitiatingProcessParentFileName:string,
    InitiatingProcessParentId:long,
    InitiatingProcessSHA1:string,
    InitiatingProcessSHA256:string,
    LocalIP:string,
    LocalPort:int,
    LogonId:long,
    MD5:string,
    MachineGroup:string,
    ProcessCommandLine:string,
    ProcessId:long,
    ProcessTokenElevation:string,
    RegistryKey:string,
    RegistryValueData:string,
    RegistryValueName:string,
    RemoteDeviceName:string,
    RemoteIP:string,
    RemotePort:int,
    RemoteUrl:string,
    ReportId:long,
    SHA1:string,
    SHA256:string,
    Timestamp:datetime,
    TimeGenerated:datetime,
    FileSize:long,
    InitiatingProcessCreationTime:datetime,
    InitiatingProcessFileSize:long,
    InitiatingProcessParentCreationTime:datetime,
    InitiatingProcessVersionInfoCompanyName:string,
    InitiatingProcessVersionInfoFileDescription:string,
    InitiatingProcessVersionInfoInternalFileName:string,
    InitiatingProcessVersionInfoOriginalFileName:string,
    InitiatingProcessVersionInfoProductName:string,
    InitiatingProcessVersionInfoProductVersion:string,
    ProcessCreationTime:datetime,
    CreatedProcessSessionId:long,
    IsProcessRemoteSession:bool,
    ProcessRemoteSessionDeviceName:string,
    ProcessRemoteSessionIP:string,
    InitiatingProcessSessionId:long,
    IsInitiatingProcessRemoteSession:bool,
    InitiatingProcessRemoteSessionDeviceName:string,
    InitiatingProcessRemoteSessionIP:string,
    InitiatingProcessUniqueId:string,
    SourceSystem:string,
    Type:string
)
["https://raw.githubusercontent.com/tom564/100_days_kql_2026/refs/heads/main/Datasets/DemoDeviceEvents.csv.gz"]
with(format="csv", ignoreFirstRecord=true);
DemoDeviceEvents
| take 5
| project new_InitiatingProcessFileName=InitiatingProcessFileName, InitiatingProcessFolderPath, FileName, ActionType, CreatedProcessSessionId
| project-away FileName
| project-by-names "new_InitiatingProcessFileName", "InitiatingProcessFolderPath", "ActionType"
| project-keep new_InitiatingProcessFileName, InitiatingProcessFolderPath
| project-rename InitiatingProcessFileName=new_InitiatingProcessFileName
| project-reorder InitiatingProcessFolderPath