// Source: https://github.com/krabelize/falco-sentinel
// Collected: 2026-05-27
// KQL Library - https://github.com/sivolko/kql-library

CommonSecurityLog
| where DeviceVendor == "Falcosecurity"
| parse-kv AdditionalExtensions as (
    ["user_loginuid"]:string,
    ["user"]:string,
    ["github-pull"]:string,
    ["-docker-config"]:string,
    ["bitbucket-pull"]:string,
    ["command"]:string,
    ["file"]:string,
    ["parent"]:string,
    ["gparent"]:string,
    ["program"]:string,
    ["pcmdline"]:string,
    ["process"]:string,
    ["cmdline"]:string,
    ["terminal"]:string,
    ["fd.name"]:string,
    ["fd.type"]:string,
    ["fd.sip"]:string,
    ["container"]:string,
    ["image"]:string,
    ["container_id"]:string,
    ["container.image.repository"]:string,
    ["k8s.ns"]:string,
    ["k8s.pod"]:string,
    ["outputfields"]:string,
    ) with (pair_delimiter=';', kv_delimiter='=', greedy=true)
| extend k8s_cluster = tostring(split(Computer, '-falcosidekick')[0])