// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-07-05
// KQL Library - https://github.com/sivolko/kql-library

let timerange=90d;
OfficeActivity
| where TimeGenerated > ago(timerange)
| where Operation in ("SecureLinkCreated", "AddedToSecureLink")
| where TargetUserOrGroupType == "Guest"
| summarize Count=count()by bin(TimeGenerated, 1d)
| render timechart with (ytitle="File Count", title="Files shared with guests over time")