// Source: https://github.com/SheriffBLN/defender-lab-framework
// Collected: 2026-05-27
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where ActionType == "UserAccountModified"
| extend AdditionalFieldsJson = parse_json(AdditionalFields)
| extend
    TargetAccount = AccountName,
    InitiatingUser = InitiatingProcessAccountName,
    InitiatingProcess = InitiatingProcessFileName,
    New_DisplayNameOrComment = tostring(AdditionalFieldsJson.DisplayName),
    PasswordLastSetRawString = tostring(AdditionalFieldsJson.PasswordLastSet),
    PasswordLastSetTime = todatetime(AdditionalFieldsJson.PasswordLastSet),
    New_PrimaryGroupId = tostring(AdditionalFieldsJson.PrimaryGroupId),
    Old_UAC = tostring(AdditionalFieldsJson.UserAccountControlFlags),
    New_UAC = tostring(AdditionalFieldsJson.NewUacValue)
| extend
    NewUAC_Decoded = case(
        New_UAC == "0x10", "Konto bez zaznaczonych opcji (domyślne ustawienia)",
        New_UAC == "0x11", "Konto jest wyłączone",
        New_UAC == "0x210", "Hasło nigdy nie wygasa",
        "Inne / Nieznane ustawienie"
    ),
    MustChangePasswordAtNextLogon = iff(PasswordLastSetRawString == "%%1794", "Tak", "Nie"),
    PasswordChangeDetected = iff(datetime_diff("minute", PasswordLastSetTime, Timestamp) == 120, "Tak", "Nie"),
    WasUACChanged = iff(Old_UAC != New_UAC, "Tak", "Nie")
| project
    Timestamp,
    DeviceName,
    TargetAccount,
    ActionType,
    InitiatingUser,
    InitiatingProcess,
    New_DisplayNameOrComment,
    PasswordLastSetRawString,
    PasswordLastSetTime,
    MustChangePasswordAtNextLogon,
    PasswordChangeDetected,
    New_PrimaryGroupId,
    Old_UAC,
    New_UAC,
    WasUACChanged,
    NewUAC_Decoded
| order by Timestamp desc