// Source: https://github.com/sivolko/kql-library
// Collected: 2026-07-07
// KQL Library - https://github.com/sivolko/kql-library

CommonSecurityLog
| where TimeGenerated > ago(7d)
| where DeviceVendor =~ "Forescout" and DeviceProduct =~ "eyeSegment"
| extend SrcZone = DeviceCustomString1,
         DstZone = DeviceCustomString2,
         Action = DeviceCustomString4
| where SrcZone != "n/a" and DstZone != "n/a"
| summarize EventCount = count(),
            UniqueSrcIPs = dcount(SourceIP),
            UniqueDstIPs = dcount(DestinationIP),
            Actions = make_set(Action)
          by SrcZone, DstZone
| order by EventCount desc