// Source: https://github.com/EmreOzanMemis/AzureSentinel
// Collected: 2026-07-06
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where ActionType == "PowerShellCommand"
| where InitiatingProcessFileName == "powershell.exe"
| where InitiatingProcessAccountName != "system"
| where AdditionalFields.Command == "Set-ExecutionPolicy"
| project TimeGenerated, DeviceName, InitiatingProcessAccountName