// Source: https://github.com/obsida-uk/Azure-BlueTeam-Toolkit
// Collected: 2026-07-03
// KQL Library - https://github.com/sivolko/kql-library

let timerange=7d;
OfficeActivity
| where TimeGenerated > ago(timerange)
| where OfficeWorkload == "OneDrive"
| where Operation in ("SecureLinkCreated", "AddedToSecureLink")
| where TargetUserOrGroupType == "Guest"
| project
    TimeGenerated,
    UserWhoShared=UserId,
    GuestWithAccess=TargetUserOrGroupName,
    OfficeObjectId