// Source: https://github.com/pluralsight-cloud/azure-automated-incident-response
// Collected: 2026-05-31
// KQL Library - https://github.com/sivolko/kql-library

    AzureActivity
    | where TimeGenerated >= ago(lookback)
    | where OperationNameValue has_any ("ipfilterrules", "securityRules", "publicIPAddresses", "firewallrules") and OperationNameValue endswith "write"
    | where ActivityStatusValue has_any ("Accept", "Accepted")
    | extend parsed_properties = parse_json(tostring(parse_json(Properties).responseBody)).properties
    | extend publicIPAddressVersion = case(Properties has_cs 'publicIPAddressVersion',tostring(parsed_properties.publicIPAddressVersion),"")
    | extend publicIPAllocationMethod = case(Properties has_cs 'publicIPAllocationMethod',tostring(parsed_properties.publicIPAllocationMethod),"")
    | extend access = case(Properties has_cs 'access',tostring(parsed_properties.access),"")
    | extend description = case(Properties has_cs 'description',tostring(parsed_properties.description),"")
    | extend destinationPortRange = case(Properties has_cs 'destinationPortRange',tostring(parsed_properties.destinationPortRange),"")
    | extend direction = case(Properties has_cs 'direction',tostring(parsed_properties.direction),"")
    | extend protocol = case(Properties has_cs 'protocol',tostring(parsed_properties.protocol),"")
    | extend sourcePortRange = case(Properties has_cs 'sourcePortRange',tostring(parsed_properties.sourcePortRange),"")
    | summarize StartTime = min(TimeGenerated), EndTime = max(TimeGenerated), ResourceIds = make_set(_ResourceId,100) by Caller, CallerIpAddress, ResourceGroup,     ActivityStatusValue, SubscriptionId, access, description, destinationPortRange, direction, protocol, sourcePortRange, publicIPAddressVersion, publicIPAllocationMethod
    | extend Name = tostring(split(Caller,'@',0)[0]), UPNSuffix = tostring(split(Caller,'@',1)[0])
    | extend Account_0_Name = Name
    | extend Account_0_UPNSuffix = UPNSuffix
    | extend IP_0_Address = CallerIpAddress
    | project Caller, CallerIpAddress, destinationPortRange, StartTime, EndTime
    | take 1