// Source: https://github.com/ugurkocde/kql_search_submissions
// Collected: 2026-05-11
// KQL Library - https://github.com/sivolko/kql-library

Syslog
| where SyslogMessage has_any ("chmod", "chown", "sudo -i", "su", "adduser", "passwd", "deluser")
| extend User = extract("USER=([^ ]+)", 1, SyslogMessage)
| extend CommandLine = extract("COMMAND=([^ ]+)", 1, SyslogMessage)
| summarize EventCount = count() by Computer, User, CommandLine 