// Source: https://github.com/RBNoronha/KQL
// Collected: 2026-07-07
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| project TimeGenerated, EventID, TargetAccount, SubjectAccount, UserAccountControl
| where EventID == "4738"
| where UserAccountControl has_any("2094", "2062")
| extend Activity = case
    (UserAccountControl contains "2094", strcat("Account Sensitivity Enabled"),
     UserAccountControl contains "2062", strcat("Account Sensitivity Disabled"),
    "Unknown")
| project TimeGenerated, Target=TargetAccount, Actor=SubjectAccount, Activity