// Source: https://github.com/ManagedSentinel/AzureSentinelKQLScripts
// Collected: 2026-05-19
// KQL Library - https://github.com/sivolko/kql-library

let timeInterval = 24h;
CommonSecurityLog
| where TimeGenerated > ago(timeInterval)
| summarize Total=count(),makeset(DeviceName)
| mv-expand set_DeviceName
| extend DeviceName=tostring(set_DeviceName)
| join kind=innerunique (CommonSecurityLog
| where TimeGenerated > ago(timeInterval)
| summarize Count=count() by DeviceName) on DeviceName
| extend percentagePerActivity = round(todouble(Count)/Total*100,2)
| project DeviceName, percentagePerActivity, totalPerActivity=Count, Total
| sort by totalPerActivity desc