// Source: https://github.com/sivolko/kql-library
// Collected: 2026-07-20
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where ((FolderPath endswith ".aspx" or FolderPath endswith ".asp" or FolderPath endswith ".php" or FolderPath endswith ".jsp" or FolderPath endswith ".jspx"))
    and (FolderPath has_any ("\inetpub\wwwroot\", "\htdocs\", "\www\", "/var/www/"))
    and  not FolderPath has_any ("\w3wp.exe", "\httpd.exe", "\nginx.exe")
| project Timestamp, DeviceName, ActionType, InitiatingProcessFolderPath, InitiatingProcessCommandLine
| limit 1000