// Source: https://github.com/Gyarbij/Artemis
// Collected: 2026-07-03
// KQL Library - https://github.com/sivolko/kql-library

IdentityLogonEvents
| where TimeGenerated > ago(7d)
| where ActionType == "LogonSuccess"
| where Protocol == "Ntlm"
| where LogonType == "Credentials validation"
| summarize ['Target Device List']=make_set(DestinationDeviceName), ['Target Device Count']=dcount(DestinationDeviceName) by DeviceName, AccountName
| sort by ['Target Device Count'] desc 

//Advanced Hunting query
IdentityLogonEvents

//Data connector required for this query - Advanced Hunting license

| where Timestamp > ago(7d)
| where ActionType == "LogonSuccess"
| where Protocol == "Ntlm"
| where LogonType == "Credentials validation"
| summarize ['Target Device List']=make_set(DestinationDeviceName), ['Target Device Count']=dcount(DestinationDeviceName) by DeviceName, AccountName
| sort by ['Target Device Count'] desc 