// Source: https://github.com/reversinglabs/reversinglabs-siem-rules
// Collected: 2026-06-02
// KQL Library - https://github.com/sivolko/kql-library

let exclusions = @'.*\\(devenv.exe|msbuild.exe|python.exe|explorer.exe|nuget.exe)$';
SysmonParser
| where EventID == 1 
| where ((Image endswith @'\MSBuild.exe' or OriginalFileName =~ @'MSBuild.exe') and not (ParentImage matches regex exclusions))
| union 
(SecurityEvent
| where EventID == 4688
| where ((NewProcessName endswith @'\MSBuild.exe') and not (ParentProcessName matches regex exclusions))),
(DeviceProcessEvents
| where ActionType == "ProcessCreated"
| where ((FolderPath endswith @'\MSBuild.exe') and not (InitiatingProcessFolderPath matches regex exclusions)))