// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-10-02
// KQL Library - https://github.com/sivolko/kql-library

IdentityInfo
| where TimeGenerated > ago(21d)
| where isnotempty(AssignedRoles)
| where AssignedRoles != "[]"
| summarize arg_max(TimeGenerated, *) by AccountUPN
| join kind=leftanti  (
    AuditLogs
    | where TimeGenerated > ago(45d)
    | where OperationName == "Add member to role completed (PIM activation)"
    | extend AccountUPN = tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)
    | summarize arg_max(TimeGenerated, *) by AccountUPN)
    on AccountUPN