// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-06-09
// KQL Library - https://github.com/sivolko/kql-library

let malware=
    OfficeActivity
    | where TimeGenerated > ago(1d)
    | where Operation == "FileMalwareDetected"
    | distinct OfficeObjectId;
OfficeActivity
| where TimeGenerated > ago (1d)
| where Operation in ("FileSyncDownloadedFull", "FileDownloaded")
| where OfficeObjectId in (malware)
| summarize ['Users who Downloaded']=make_set(UserId) by ['File Name']=OfficeObjectId