// Source: https://github.com/rod-trent/Sentinel-SOC-101
// Collected: 2026-07-25
// KQL Library - https://github.com/sivolko/kql-library

view all legacy authentication events from a specific user:

SecurityEvent  
| where EventID == 4624 and TargetLogonId != 0x0 and AccountName == "<username>"  
| extend LegacyAuthentication = iif((LogonProcessName =~ "Advapi" or LogonProcessName =~ "Ssp"), "True", "False")  
| where LegacyAuthentication == "True"  