// Source: https://github.com/shubhendushubham/kali-browser
// Collected: 2026-10-02
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where EventID == 4738
| where AccountType == "User"
| where UserAccountControl has_any ("2064", "2096")
| extend Action = case(UserAccountControl has "2096", strcat("Kerberos preauthentication disabled"),
    UserAccountControl has "2064", strcat("Kerberos preauthentication enabled"),
    "unknown")
| project TimeGenerated, Actor=SubjectAccount, User=TargetAccount, Action