// Source: https://github.com/DancinDinoo/KQL
// Collected: 2026-06-07
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where EventID in ("4756", "4728", "4732")
| where TargetUserName in~ ("Enterprise Admins", "Domain Admins", "Schema Admins", "Adminstrators")
| project TimeGenerated, AccountType, UserAdded = Account, TargetGroup = TargetUserName, Activity, Computer, MemberName