// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-05-22
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where ActionType == "SecurityLogCleared"
| project
    TimeGenerated,
    DeviceName,
    InitiatingProcessAccountDomain,
    InitiatingProcessAccountName

//Advanced Hunting query

//Data connector required for this query - Advanced Hunting license

DeviceEvents
| where ActionType == "SecurityLogCleared"
| project
    Timestamp,
    DeviceName,
    InitiatingProcessAccountDomain,
    InitiatingProcessAccountName