// Source: https://github.com/SlimKQL/Hunting-Queries-Detection-Rules
// Collected: 2026-07-12
// KQL Library - https://github.com/sivolko/kql-library

let QueryPeriod = 1h;
let dMSARegKey = dynamic(["DelegatedMSAEnabled"]);
let dMSAMonitor =
SecurityEvent
| where TimeGenerated > ago(QueryPeriod)
| where EventID == 307 or // dMSA Migration
EventID == 308 or // dMSA Permission Add
EventID == 309; // dMSA Key Fetch
DeviceRegistryEvents
| where TimeGenerated > ago(QueryPeriod)
| where ActionType == @"RegistryKeyCreated" or ActionType  == @"RegistryValueSet"
| where RegistryKey has_any(dMSARegKey)
| union dMSAMonitor