// Source: https://github.com/sivolko/kql-library
// Collected: 2026-07-25
// KQL Library - https://github.com/sivolko/kql-library

let CompromisedDevice = "";
let SearchWindow = 30d; //Customizable h = hours, d = days
IdentityLogonEvents
| where Timestamp > (now() - SearchWindow)
| where DeviceName == CompromisedDevice
| summarize
     TotalDevicesAccessed = dcount(DestinationDeviceName),
     DevicesAccessed = make_set(DestinationDeviceName),
     ProtocolsUsed = make_set(Protocol)
     by DeviceName