// Source: https://github.com/Gyarbij/Artemis
// Collected: 2026-07-07
// KQL Library - https://github.com/sivolko/kql-library

OfficeActivity
| where TimeGenerated > ago (30d)
| where Operation in ("FileSyncDownloadedFull", "FileDownloaded")
| where UserId contains "#ext#"
| summarize Count=count()by FileName=SourceFileName
| sort by Count desc
| take 20
| render barchart with (title="Top files downloaded by guests over the last month")