// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-05-22
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where ActionType == "CredentialsBackup"
| project
    TimeGenerated,
    DeviceName,
    InitiatingProcessAccountName,
    InitiatingProcessCommandLine,
    InitiatingProcessFileName,
    InitiatingProcessFolderPath

//Advanced Hunting query

//Data connector required for this query - Advanced Hunting license

DeviceEvents
| where ActionType == "CredentialsBackup"
| project
    Timestamp,
    DeviceName,
    InitiatingProcessAccountName,
    InitiatingProcessCommandLine,
    InitiatingProcessFileName,
    InitiatingProcessFolderPath