// Source: https://github.com/gennaromigliaccio/Microsoft-Sentinel
// Collected: 2026-05-27
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where Timestamp >= ago(30d)
| where ActionType startswith "Asr"
| extend AsrRuleDisplay = case(
    ActionType == "AsrOfficeMacroWin32ApiBlocked",                     "Block Win32 API calls from Office macros",
    ActionType == "AsrChildProcessBlocked",                             "Block Office apps from creating child processes",
    ActionType == "AsrOfficeCommunicationAppChildProcessBlocked",       "Block Office communication apps from creating child processes",
    ActionType == "AsrAdobeReaderChildProcessBlocked",                  "Block Adobe Reader from creating child processes",
    ActionType == "AsrExecutableObfuscatedOrTamperedBlocked",           "Block executable content with obfuscated/tampered code",
    ActionType == "AsrExecutableFromEmailOrWebmailBlocked",             "Block executable content from email and webmail",
    ActionType == "AsrUntrustedUsbBlocked",                             "Block untrusted/unsigned processes from USB",
    ActionType == "AsrLsassCredentialTheftBlocked",                     "Block credential stealing from LSASS",
    ActionType == "AsrScriptedContentBlocked",                          "Block JavaScript or VBScript from launching downloaded content",
    ActionType == "AsrRansomwareMitigationAudited",                     "Use advanced protection against ransomware (audit)",
    ActionType == "AsrRansomwareMitigationBlocked",                     "Use advanced protection against ransomware (block)",
    ActionType == "AsrWebShellCreationBlocked",                         "Block web shell creation (Server)",
    ActionType
)
| summarize
    Events = count(),
    FirstSeen = min(Timestamp),
    LastSeen = max(Timestamp)
  by DeviceName, AsrRuleDisplay