// Source: https://github.com/MorganCPatz/KQL-Queries
// Collected: 2026-07-03
// KQL Library - https://github.com/sivolko/kql-library

SigninLogs
| where TimeGenerated > ago (30d)
| where ConditionalAccessStatus == "failure"
| where (isnotempty(DeviceDetail.trustType) and isnotempty(LocationDetails.countryOrRegion))
| extend Country = tostring(LocationDetails.countryOrRegion),
    State = tostring(LocationDetails.state),
    City = tostring(LocationDetails.city)
| where Country != "US"
| summarize FailedLogins = count() by Country, State, City
| top 10 by FailedLogins