// Source: https://github.com/kehaitcfyn/DefenderXDR
// Collected: 2026-05-30
// KQL Library - https://github.com/sivolko/kql-library

let DLLLoaded =
DeviceEvents
| where Timestamp > ago(1h)
| where ActionType == @"DriverLoad"
| where FileName endswith ".dll"
| distinct FileName;
DeviceRegistryEvents
| where ActionType == @"RegistryKeyCreated" or ActionType == @"RegistryValueSet"
| where RegistryKey has_any(DLLLoaded)
