// Source: https://github.com/obsida-uk/Azure-BlueTeam-Toolkit
// Collected: 2026-07-26
// KQL Library - https://github.com/sivolko/kql-library

let timerange=30d;
SigninLogs
| where TimeGenerated > ago(timerange)
| project TimeGenerated, UserType, ResultType, AppDisplayName
| where ResultType == 0
| summarize
    MemberSignins=countif(UserType == "Member"),
    GuestSignins=countif(UserType == "Guest")
    by AppDisplayName
| sort by AppDisplayName  