// Source: https://github.com/troytrojan01/ot-cybersecurity-with-sentinel
// Collected: 2026-07-07
// KQL Library - https://github.com/sivolko/kql-library

CommonSecurityLog
| where TimeGenerated > ago(7d)
| where DeviceVendor =~ "Forescout" and DeviceProduct =~ "eyeInspect"
| extend EngineeringTool = tostring(column_ifexists("DeviceProcessName", ""))
| where isnotempty(EngineeringTool)
| extend HourLocal = hourofday(TimeGenerated),
         DayOfWeek = dayofweek(TimeGenerated)
| where HourLocal < 7 or HourLocal >= 19          // before 7am or after 7pm
     or DayOfWeek == 0d or DayOfWeek == 6d         // weekend
| project TimeGenerated, HourLocal, DayOfWeek,
          EngineeringTool,
          Activity,
          SourceIP,
          DestinationIP,
          DstAssetRole = DeviceCustomString2,
          Message
| order by TimeGenerated desc