// Source: https://github.com/ManagedSentinel/AzureSentinelKQLScripts
// Collected: 2026-05-10
// KQL Hunter - https://github.com/YOUR_USER/kql-hunter

CommonSecurityLog
| extend AdditionalExtensions = extract_all(@"(?P<key>\w+)=(?P<value>\w+)", dynamic(["key","value"]), AdditionalExtensions)
| mv-apply AdditionalExtensions on (
    summarize AdditionalExtensionsParsed = make_bag(pack(tostring(AdditionalExtensions[0]), AdditionalExtensions[1]))
)