// Source: https://github.com/ITProfessorCloud/Microsoft-Sentinel
// Collected: 2026-06-09
// KQL Library - https://github.com/sivolko/kql-library

let AccountUPN = "username@domain.com";
let SearchWindow = 30d;
AuditLogs
| where TimeGenerated > ago(SearchWindow)
| extend InitiatingUser = parse_json(InitiatedBy.user)
| extend InitiatingUPN = tostring(InitiatingUser.userPrincipalName)
| where InitiatingUPN == AccountUPN
| project TimeGenerated, InitiatingUPN, OperationName, ResultDescription, ActivityDisplayName, Resource, Result