// Source: https://github.com/ITProfessorCloud/Microsoft-Sentinel
// Collected: 2026-07-25
// KQL Library - https://github.com/sivolko/kql-library

let UserPrincipalName_ = "user@domain.com"; 
OfficeActivity
| where Operation in ("SecureLinkCreated", "AddedToSecureLink", "SharingLinkUpdated", "SharingLinkCreated", "AnonymousLinkCreated") 
| where UserId has UserPrincipalName_ 
| summarize GuestShares = count(), 
           SharedLinks = make_set(OfficeObjectId), 
            SharedToUsers = make_set(TargetUserOrGroupName) by bin(TimeGenerated, 1d), Sharer = UserId
| sort by TimeGenerated desc