// Source: https://github.com/THESunnyNguyen/kql-hunting-queries
// Collected: 2026-05-19
// KQL Library - https://github.com/sivolko/kql-library

let lookback = 7d;
let highImpactPermissions = dynamic([
  "Mail.Read",
  "Mail.ReadWrite",
  "Files.Read.All",
  "Files.ReadWrite.All",
  "Directory.Read.All",
  "Directory.ReadWrite.All",
  "offline_access",
  "User.ReadWrite.All"
]);
AuditLogs
| where TimeGenerated >= ago(lookback)
| where OperationName has_any ("Consent to application", "Add delegated permission grant", "Add app role assignment to service principal")
| extend InitiatedByUser = tostring(InitiatedBy.user.userPrincipalName)
| extend InitiatedByApp = tostring(InitiatedBy.app.displayName)
| extend TargetText = tostring(TargetResources)
| where TargetText has_any (highImpactPermissions)
| project TimeGenerated, OperationName, Result, InitiatedByUser, InitiatedByApp, TargetText, CorrelationId
| order by TimeGenerated desc
