// Source: https://github.com/reversinglabs/reversinglabs-siem-rules
// Collected: 2026-06-24
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where EventID == 4688
| where Process matches regex "rufus-.*.exe"
| project TimeGenerated, Computer, Account=SubjectUserName, AccountDomain=SubjectDomainName, Process, NewProcessName, ParentProcessName, ProcessId=tolong(NewProcessId), TokenElevationType, Type
| union 
(DeviceProcessEvents
| where FileName matches regex "rufus-.*.exe"
| project TimeGenerated, Computer=DeviceName, Account=AccountName, AccountDomain, Process=FileName, NewProcessName=FolderPath, ParentProcessName=InitiatingProcessFolderPath, ProcessId, MD5, SHA1, SHA256, Type)
| project TimeGenerated, Computer, Account, AccountDomain, Process, NewProcessName, ParentProcessName, ProcessId, MD5, SHA1, SHA256, Type