// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-05-22
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where TimeGenerated > ago(30d)
| where ActionType startswith "Asr"
| where isnotempty(InitiatingProcessCommandLine)
| summarize ['ASR Hit Count']=count()by ActionType, InitiatingProcessCommandLine
| sort by ['ASR Hit Count'] desc 

//Advanced Hunting query

//Data connector required for this query - Advanced Hunting license

DeviceEvents
| where TimeGenerated > ago(30d)
| where ActionType startswith "Asr"
| where isnotempty(InitiatingProcessCommandLine)
| summarize ['ASR Hit Count']=count()by ActionType, InitiatingProcessCommandLine
| sort by ['ASR Hit Count'] desc 