// Source: https://github.com/DancinDinoo/KQL
// Collected: 2026-05-26
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
  | where ActionType == 'UserAccountAddedToLocalGroup' 
  | extend GroupSid = tostring(AdditionalFields.GroupSid) | where GroupSid == "S-1-5-32-544"
  | where InitiatingProcessAccountName !contains DeviceName and InitiatingProcessAccountName !contains "$" // Local machine accounts
  | project AccountAddedTime = TimeGenerated, AddedAccountSid = AccountSid, DeviceId, DeviceName, AddingAccount = InitiatingProcessAccountName, AddingAccountSid = InitiatingProcessAccountSid

// Description: Detects a user being added to the local administrators group on a device