// Source: https://github.com/syedmustafa22/azure-soc-sentinel-lab
// Collected: 2026-06-02
// KQL Library - https://github.com/sivolko/kql-library

let GeoIPDB_FULL = _GetWatchlist("geoip");
let WindowsEvents = SecurityEvent
    | where EventID == 4625
    | order by TimeGenerated desc
    | evaluate ipv4_lookup(GeoIPDB_FULL, IpAddress, network);
WindowsEvents
| project Computer, AttackerIp = IpAddress, cityname, countryname, latitude, longitude