// Source: https://github.com/vivekrn11/AzureSentinelKQLqueries
// Collected: 2026-06-29
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where TimeGenerated > ago (7d)
| where AccountType == "User"
| where EventID in (4728, 4732, 4756, 4761, 4746, 4751)
| project TimeGenerated, MemberName, ['Group Name']=TargetUserName, EventID, Account, Computer, EventData, Activity, MemberSid
| parse MemberName with * 'CN=' UserAdded ',' *
| summarize UsersAdded=make_set(UserAdded) by ['Group Name'], startofday(TimeGenerated),  EventID, Account, Computer, EventData, Activity, MemberSid
| sort by ['Group Name'] asc, TimeGenerated desc 