// Source: https://github.com/ge0mant1s/SOaC-Enterprise
// Collected: 2026-05-21
// KQL Library - https://github.com/sivolko/kql-library

let WebExploit = CommonSecurityLog | where TimeGenerated > ago(1h) | where DeviceVendor == "WAF" | where LogSeverity >= 7; let ProcessInject = DeviceProcessEvents | where Timestamp > ago(1h) | where ProcessCommandLine contains "CreateRemoteThread"; let MetadataAccess = AWSCloudTrail | where TimeGenerated > ago(1h) | where RequestURI contains "169.254.169.254"; WebExploit | join kind=inner (ProcessInject) on $left.SourceIP == $right.RemoteIP | join kind=inner (MetadataAccess) on $left.SourceIP == $right.SourceIPAddress