// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-07-28
// KQL Library - https://github.com/sivolko/kql-library

SigninLogs
| where TimeGenerated > ago (30d)
| where AuthenticationRequirement == "multiFactorAuthentication"
| project AuthenticationDetails
| extend ['MFA Method'] = tostring(parse_json(AuthenticationDetails)[1].authenticationMethod)
| summarize Count=count()by ['MFA Method']
| where ['MFA Method'] != "Previously satisfied" and isnotempty(['MFA Method'])
| sort by Count desc
| render barchart with (title="Types of MFA Methods used")