// Source: https://github.com/threatsignal/Intel
// Collected: 2026-07-14
// KQL Library - https://github.com/sivolko/kql-library

CommonSecurityLog
| where DeviceVendor == "Check Point"
| where AdditionalExtensions has "ike_version=IKEv1" or Message has "IKEv1"
| extend duration = extract(@"phase1_duration_ms=(\d+)", 1, AdditionalExtensions, typeof(int))
| where duration < 1000
| project TimeGenerated, SourceIP, DestinationIP, duration, Message