// Source: https://github.com/ValioCH/Hybrid-Cloud-SOC-Sentinel
// Collected: 2026-07-21
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where EventID == 4688 // Process Creation
| where ProcessName has "powershell.exe"
| where CommandLine has "-ExecutionPolicy Bypass" or CommandLine has "-ep Bypass"
| project TimeGenerated, Computer, SubjectUserName, ProcessName, CommandLine
| sort by TimeGenerated desc