// Source: https://github.com/petitess/kusto
// Collected: 2026-05-10
// KQL Hunter - https://github.com/YOUR_USER/kql-hunter

SecurityEvent
| project TimeGenerated, EventID, TargetAccount, SubjectAccount, UserAccountControl
| where EventID == "4738"
| where UserAccountControl has ("2082")
| extend Activity = strcat("Account set to password not required")
| project TimeGenerated, Target=TargetAccount, Actor=SubjectAccount, Activity