// Source: https://github.com/sivolko/kql-library
// Collected: 2026-06-28
// KQL Library - https://github.com/sivolko/kql-library

let timeWindow = 15m;
Zabbix_Events_CL
| where TimeGenerated > ago(timeWindow)
| where Severity == "High" or Severity == "Disaster"
| join kind=inner (
    SecurityEvent
    | where TimeGenerated > ago(timeWindow)
    | where EventID in (4688, 4625, 4624) // suspicious logons, process creation
) on Computer
| project TimeGenerated, Computer, Severity, Problem=ProblemName, SecurityEventID=EventID, Account, LogonType, Process