// Source: https://github.com/ChrFrohn/KQL
// Collected: 2026-07-21
// KQL Library - https://github.com/sivolko/kql-library

AuditLogs
| where OperationName contains "Update user"
| extend UpdateInfo = tostring(TargetResources[0].modifiedProperties)
| extend UpdateInfo = parse_json(tostring(TargetResources[0].modifiedProperties))
| extend Initiater = tostring(InitiatedBy.user.userPrincipalName)
| mv-expand UpdateInfo
| where UpdateInfo.displayName == "TelephoneNumber"
| project Initiater, UpdatedAttribute = UpdateInfo.newValue