// Source: https://github.com/THESunnyNguyen/kql-hunting-queries
// Collected: 2026-06-11
// KQL Library - https://github.com/sivolko/kql-library

let lookback = 1d;
let maxHoursBetweenCountries = 8.0;
SigninLogs
| where TimeGenerated >= ago(lookback)
| where ResultType == 0
| extend City = tostring(LocationDetails.city)
| extend Country = tostring(LocationDetails.countryOrRegion)
| where isnotempty(UserPrincipalName) and isnotempty(IPAddress) and isnotempty(Country)
| project TimeGenerated, UserPrincipalName, IPAddress, AppDisplayName, City, Country, ClientAppUsed, UserAgent
| sort by UserPrincipalName asc, TimeGenerated asc
| serialize
| extend PreviousTime = prev(TimeGenerated)
| extend PreviousUser = prev(UserPrincipalName)
| extend PreviousIPAddress = prev(IPAddress)
| extend PreviousCity = prev(City)
| extend PreviousCountry = prev(Country)
| where UserPrincipalName == PreviousUser and Country != PreviousCountry
| extend HoursBetween = datetime_diff("second", TimeGenerated, PreviousTime) / 3600.0
| where HoursBetween between (0.01 .. maxHoursBetweenCountries)
| project TimeGenerated, UserPrincipalName, IPAddress, Country, City, PreviousTime, PreviousIPAddress, PreviousCountry, PreviousCity, HoursBetween, AppDisplayName, ClientAppUsed, UserAgent
