// Source: https://github.com/obsida-uk/Azure-BlueTeam-Toolkit
// Collected: 2026-05-31
// KQL Library - https://github.com/sivolko/kql-library

AzureActivity
| where OperationNameValue == "MICROSOFT.OPERATIONALINSIGHTS/WORKSPACES/SHAREDKEYS/ACTION"
| extend WorkspaceName = tostring(parse_json(Properties).resource)
| where ActivityStatusValue == "Success"
| project
    TimeGenerated,
    Actor=Caller,
    ActorIPAddress=CallerIpAddress,
    WorkspaceName,
    SubscriptionId,
    ResourceGroup