// Source: https://github.com/Gyarbij/Artemis
// Collected: 2026-06-05
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where EventID == "4742"
| parse EventData with * 'NewUacValue">' NewUacValue '</Data>' *
| parse EventData with * 'TargetUserName">' ComputerName '</Data>' *
| parse EventData with * 'SubjectUserName">' Actor '</Data>' *
| where NewUacValue == "0x2080"
| project TimeGenerated, Activity, ComputerName, Actor