// Source: https://github.com/microsoft/AzureMonitorCommunity
// Collected: 2026-05-30
// KQL Library - https://github.com/sivolko/kql-library

AzureActivity 
| where OperationNameValue in ("MICROSOFT.DATAFACTORY/FACTORIES/PIPELINES/WRITE","MICROSOFT.DATAFACTORY/FACTORIES/PIPELINES/DELETE")
| summarize arg_max(TimeGenerated, *) by CorrelationId
| extend Res=tostring(Properties_d.resource),
         Op=tostring(trim_start("MICROSOFT.DATAFACTORY/FACTORIES/PIPELINES/", OperationNameValue))
| where Res has "ADF Name"                        // replace with the name of your ADF
| project TimeGenerated, ResourceGroup, Caller, Res, ActivityStatusValue, Op