// Source: https://github.com/le0li9ht/Microsoft-Sentinel-Queries
// Collected: 2026-05-24
// KQL Library - https://github.com/sivolko/kql-library

AzureActivity 
| where OperationNameValue contains "Microsoft.ContainerService/managedClusters/listClusterAdminCredential/action" 


AzureDiagnostics 
| where Category == "kube-audit" 
| extend logs=parse_json(log_s) 
| where logs.user.username == "masterclient"