// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-08-09
// KQL Library - https://github.com/sivolko/kql-library

AuditLogs
| where OperationName has "Add member to role outside of PIM"
| extend RoleName = tostring(TargetResources[0].displayName)
| extend UserAdded = tostring(TargetResources[2].displayName)
| extend Actor = tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)
| project TimeGenerated, OperationName, RoleName, UserAdded, Actor