// Source: https://github.com/EternalR00ted/Microsoft-Sentinel-KQLs
// Collected: 2026-06-28
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where ActionType == "NamedPipeEvent"
| where AdditionalFields has "REDSUN"
| project Timestamp, DeviceId, ReportId, DeviceName,
          InitiatingProcessFileName, InitiatingProcessCommandLine,
          InitiatingProcessAccountName, AdditionalFields