// Source: https://github.com/chadmcox/Sentinel-and-Defender-Queries
// Collected: 2026-05-27
// KQL Library - https://github.com/sivolko/kql-library

let list = IdentityInfo
| where AssignedRoles contains "Global Administrator"
| where OnPremSid contains "S-1-5-21"
| distinct OnPremSid;
IdentityLogonEvents 
| where AccountSid in (list)
| project Timestamp, ActionType, AccountUpn, LogonType, DeviceName, TargetDeviceName
| sort by Timestamp