// Source: https://github.com/rod-trent/Sentinel-SOC-101
// Collected: 2026-08-30
// KQL Library - https://github.com/sivolko/kql-library

OfficeActivity
| where TimeGenerated > ago(30d)
| where Operation in ("Send", "Receive", "Download", "Upload", "Accessed", "Modified", "Renamed", "Deleted", "Shared", "Unshared")
| summarize Users=dcount(UserId), UserAgents=dcount(UserAgent), Records=count() by OrganizationName
| extend DomainLength = strlen(OrganizationName)
| extend Entropy = DomainLength * 1.0 / array_length(split(OrganizationName, ""))
| where Entropy > 3.5
| order by Users asc
| take 10