// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-07-27
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where ActionType == "PowerShellCommand"
| where InitiatingProcessFileName == "powershell.exe"
| where InitiatingProcessAccountName != "system"
| where AdditionalFields.Command == "Set-ExecutionPolicy"
| project TimeGenerated, DeviceName, InitiatingProcessAccountName