// Source: https://github.com/xpinux/Project-SABER
// Collected: 2026-05-28
// KQL Library - https://github.com/sivolko/kql-library

Syslog
| where SyslogMessage contains  @"/p/u/doAuthentication.do"
|union (
    CommonSecurityLog
    | where RequestURL contains "/p/u/doAuthentication.do"
    | where Activity <> "Activity mitigated"
    | where DeviceAction <> "block"
    | project TimeGenerated, DeviceVendor, RequestURL, RequestMethod, SourceIP, DestinationIP,DeviceAction
)