// Source: https://github.com/reversinglabs/reversinglabs-siem-rules
// Collected: 2026-06-28
// KQL Library - https://github.com/sivolko/kql-library

let Domains = externaldata(Domain: string) [h"https://raw.githubusercontent.com/reversinglabs/reversinglabs-siem-rules/master/Malware/SmokeLoader/20230724/KQL/smokeloader-20230724-c2domains.txt"];
CommonSecurityLog
| where DestinationHostName in (Domains)
| union
(SysmonParser 
| where EventID == 22 
| where QueryName in (Domains))