// Source: https://github.com/ep3p/Sentinel_KQL
// Collected: 2026-07-22
// KQL Library - https://github.com/sivolko/kql-library

let _BenignFilesRegex = toscalar(
    _GetWatchlist('Activity-ExpectedSignificantActivity')
    | where Activity == "SharePointFileMalwareDetected"
    | summarize RegEx = make_list(Auxiliar)
    | project RegEx = strcat(@'^(', strcat_array(RegEx, '|'), @')$')
);
OfficeActivity
| where Operation == "FileMalwareDetected"
| extend AlertSeverity = case(
    SourceFileName matches regex _BenignFilesRegex, "Informational",
    "Medium"
    )
| project
    TimeGenerated,
    Operation,
    Site_Url,
    SourceFileName,
    SourceFileExtension,
    ContainerUrl = strcat(Site_Url, SourceRelativeUrl),
    OfficeObjectId,
    AlertSeverity