// Source: https://github.com/rod-trent/Security-Copilot
// Collected: 2026-06-11
// KQL Library - https://github.com/sivolko/kql-library

SigninLogs 
| where TimeGenerated >= ago(24h) 
| where AppDisplayName == "Medeina Portal" 
| where ResultType == "50074" 
| extend city = LocationDetails.city 
| extend state = LocationDetails.state 
| extend region = LocationDetails.countryOrRegion 
| extend latitude = parse_json(tostring(LocationDetails.geoCoordinates)).latitude 
| extend longitude = parse_json(tostring(LocationDetails.geoCoordinates)).longitude 
| project UserDisplayName, UserPrincipalName, UserType, city, state, region, latitude, longitude, AADTenantId