// Source: https://github.com/sivolko/kql-library
// Collected: 2026-06-03
// KQL Library - https://github.com/sivolko/kql-library

let StartDate = startofday(ago(1d));
let EndDate = startofday(now());
union DeviceRegistryEvents,DeviceProcessEvents,DeviceNetworkEvents,DeviceLogonEvents,DeviceImageLoadEvents,DeviceEvents,
DeviceFileEvents,BehaviorEntities,BehaviorInfo,EmailPostDeliveryEvents,UrlClickEvents,IdentityDirectoryEvents,IdentityQueryEvents,
IdentityLogonEvents,CloudAppEvents,DeviceCustomFileEvents,DeviceCustomNetworkEvents,AADRiskyUsers,DeviceCustomScriptEvents,
AzureActivity,AADUserRiskEvents,SecurityEvent,AADManagedIdentitySignInLogs,BehaviorAnalytics,SigninLogs,
AADNonInteractiveUserSignInLogs,SentinelHealth,MicrosoftServicePrincipalSignInLogs,AADServicePrincipalSignInLogs,
AzureDiagnostics,IntuneDevices,AuditLogs,IntuneDeviceComplianceOrg 
| where TimeGenerated between (StartDate .. EndDate)
| extend Action = coalesce(OperationName, OperationNameValue, ActionType, tostring(EventID)) 
| where isnotempty(Action) 
| summarize TotalEvents = count() by Type, Action
| extend RetrievalDate = StartDate, TableName = Type
| sort by TableName