// Source: https://github.com/vivekrn11/AzureSentinelKQLqueries
// Collected: 2026-07-21
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where TimeGenerated > ago(7d)
| where EventID == "4624"
| where LogonType == 10
//Extend new column that drops Account to lower case so users are correctly summarized, i.e User123 and user123 are combined
| extend AccountName=tolower(Account)
| summarize
    ['Count of Computers']=dcount(Computer),
    ['List of Computers']=make_set(Computer)
    by AccountName
| sort by ['Count of Computers'] desc 