// Source: https://github.com/CyberAutomationX/SecureAzCloud-Scripts
// Collected: 2026-07-07
// KQL Library - https://github.com/sivolko/kql-library

let Lookback = 30d;
AzureActivity
| where TimeGenerated > ago(Lookback)
| extend Operation_l = tolower(OperationNameValue),
         Provider_l = tolower(ResourceProviderValue)
| where Provider_l has "microsoft.cognitiveservices"
| where Operation_l has "deployments/delete" or (ResourceId has "/deployments/" and Operation_l has "/delete")
| project TimeGenerated, Caller, CallerIpAddress, OperationNameValue, ActivityStatusValue, SubscriptionId, ResourceGroup, ResourceId, Properties_d
| sort by TimeGenerated desc