// Source: https://github.com/SlimKQL/Hunting-Queries-Detection-Rules
// Collected: 2026-05-10
// KQL Hunter - https://github.com/YOUR_USER/kql-hunter

let DangerousAdmin =
ExposureGraphNodes
| where set_has_element(Categories, "identity")
| extend AccountUPN = NodeProperties.rawData.accountUpn
| extend AdminRoles = NodeProperties.rawData.assignedRoles
| where AdminRoles contains "Partner Tier2 Support"
| project AccountUPN;
IdentityLogonEvents
| where AccountUpn has_any(DangerousAdmin)

// MITRE ATT&CK Mapping

// T1078.004: Valid Accounts: Cloud Accounts - Identifying and monitoring privileged accounts in cloud environments.
// T1078: Valid Accounts - Monitoring logon events for suspicious activity.
// T1078.001: Valid Accounts: Domain Accounts - Tracking logon events for domain accounts.