// Source: https://github.com/reversinglabs/reversinglabs-siem-rules
// Collected: 2026-05-20
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where EventID == 4688
| where Process == "powershell.exe" 
| where CommandLine contains "-ExecutionPolicy Bypass -command Copy-Item" and CommandLine matches regex @"(?i)C:\\users\\.*\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup.*"
| extend SourceFile = extract(@"-ExecutionPolicy Bypass -command Copy-Item '(.*?)' ", 1, CommandLine)
| where SourceFile == ParentProcessName
| union 
(DeviceProcessEvents
| where ActionType == "ProcessCreated"
| where FileName contains "powershell.exe"
| where ProcessCommandLine contains "-ExecutionPolicy Bypass -command Copy-Item" and ProcessCommandLine matches regex @"(?i)C:\\users\\.*\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup.*"
| extend SourceFile = extract(@"-ExecutionPolicy Bypass -command Copy-Item '(.*?)' ", 1, ProcessCommandLine)
| where tolower(SourceFile) == InitiatingProcessFolderPath),
(SysmonParser
| where EventID == 1
| where OriginalFileName contains "powershell.exe"
| where CommandLine contains "-ExecutionPolicy Bypass -command Copy-Item" and CommandLine matches regex @"(?i)C:\\users\\.*\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup.*"
| extend SourceFile = extract(@"-ExecutionPolicy Bypass -command Copy-Item '(.*?)' ", 1, CommandLine)
| where SourceFile == ParentImage)