// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-07-28
// KQL Library - https://github.com/sivolko/kql-library

AuditLogs
| where TimeGenerated > ago(1d)
| where OperationName == "Create access package"
| where TargetResources[0].type == "AccessPackage"
| extend AccessPackageName = tostring(TargetResources[0].displayName)
| extend Actor = tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)
| project TimeGenerated, OperationName, AccessPackageName, Actor