// Source: https://github.com/pirateape/Azure-Security
// Collected: 2026-05-20
// KQL Library - https://github.com/sivolko/kql-library

OfficeActivity
| where TimeGenerated > ago(1h)
| where OfficeWorkload == "Exchange"
| where Operation in ("SoftDelete", "HardDelete", "MoveToDeletedItems")
| summarize
    DeletedItems   = count(),
    DeletedFolders = make_set(tostring(Item.ParentFolder.Path)),
    IPs            = make_set(ClientIP)
  by UserId, bin(TimeGenerated, 10m)
| where DeletedItems > 50
| order by DeletedItems desc