// Source: https://github.com/chadmcox/Azure_Active_Directory
// Collected: 2026-07-11
// KQL Library - https://github.com/sivolko/kql-library

let timerange=30d;
SigninLogs
| where TimeGenerated > ago(timerange)
| where ResultType == 0
| where UserType == "Guest"
| where RiskLevelDuringSignIn <> "none"
| project AppDisplayName, UserPrincipalName, RiskLevelAggregated, RiskLevelDuringSignIn, RiskState, RiskDetail, RiskEventTypes_V2,MfaDetail,ConditionalAccessStatus,AuthenticationRequirement