// Source: https://github.com/sivolko/kql-library
// Collected: 2026-05-23
// KQL Library - https://github.com/sivolko/kql-library

union (
    DeviceNetworkEvents
    | project DeviceId, Timestamp, DeviceName
), (
    DeviceInfo
    | project DeviceId, Timestamp, DeviceName
), (
    DeviceEvents
    | project DeviceId, Timestamp, DeviceName
)
| summarize LastSeen = max(Timestamp) by DeviceId, DeviceName
| project DeviceId, LastSeen, DeviceName