// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-06-09
// KQL Library - https://github.com/sivolko/kql-library

OfficeActivity
| where TimeGenerated > ago(30d)
| project TimeGenerated, Operation
| where Operation in ("FileSyncDownloadedFull", "FileSyncUploadedFull", "FileDownloaded", "FileUploaded")
| summarize
    ['Files Downloaded']=countif(Operation in ("FileDownloaded", "FileSyncDownloadedFull")),
    ['Files Uploaded']=countif(Operation in ("FileSyncUploadedFull", "FileUploaded"))
    by startofday(TimeGenerated)
| render columnchart
    with (
    kind=unstacked,
    title="Downloads vs Uploads in Office 365",
    ytitle="Count",
    xtitle="Day")