// Source: https://github.com/kkroth0/threat-hunting-ptbr
// Collected: 2026-07-18
// KQL Library - https://github.com/sivolko/kql-library

let lookback = 14d;
let huntId = "H144";
let sourceUrl = "https://github.com/THORCollective/HEARTH/blob/main/Flames/H144.md";
let huntTerms = dynamic(["T1056.003", "T1185", "ui automation", "coyote", "browser session hijacking", "H144", "abusing", "Windows", "Automation", "framework", "read", "foreground", "browser", "address", "non-AT", "process", "trigger", "banking-session", "hijacking", "when", "targeted", "domains"]);
union withsource=SourceTable isfuzzy=true
    SecurityEvent,
    WindowsEvent,
    TrendMicro_XDR_OAT_CL,
    TrendMicro_XDR_WORKBENCH_CL,
    ThreatIntelIndicators,
    Watchlist,
    SecurityAlert,
    SecurityIncident,
    Anomalies,
    Syslog,
    Heartbeat,
    CommonSecurityLog
| where TimeGenerated >= ago(lookback)
| extend SearchBlob = tostring(pack_all())
| where SearchBlob has_any (huntTerms)
| extend HuntId = huntId, SourceUrl = sourceUrl
| project TimeGenerated, HuntId, SourceTable, SourceUrl, SearchBlob
| order by TimeGenerated desc