// Source: https://github.com/kkroth0/threat-hunting-ptbr
// Collected: 2026-07-15
// KQL Library - https://github.com/sivolko/kql-library

let lookback = 7d;
let huntTerms = dynamic(["T1218.005", "defenseevasion", "systembinaryproxyexecutionmshta", "H009", "Attackers", "exploit", "mshta.exe", "trusted", "Windows", "utility", "execute", "malicious", "files", "well", "JavaScript", "VBScript", "indirectly", "Mshta.exe", "designed", "Microsoft", "HTML", "Applications", "powershell", "cmd.exe", "wscript", "cscript", "mshta", "rundll32", "regsvr32", "CurrentVersion\\Run", "Scheduled", "Service", "Registry"]);
union withsource=SourceTable isfuzzy=true
    SecurityEvent,
    WindowsEvent,
    TrendMicro_XDR_OAT_CL,
    TrendMicro_XDR_WORKBENCH_CL
| where TimeGenerated >= ago(lookback)
| extend SearchBlob = tostring(pack_all())
| where SearchBlob has_any (huntTerms)
| extend HuntId = "H009", SourceUrl = "https://github.com/THORCollective/HEARTH/blob/main/Flames/H009.md"
| project TimeGenerated, HuntId, SourceTable, SourceUrl, SearchBlob
| order by TimeGenerated desc