// Source: https://github.com/chadmcox/Azure_Active_Directory
// Collected: 2026-06-11
// KQL Library - https://github.com/sivolko/kql-library

SigninLogs | where TimeGenerated > ago(14d) | where RiskState == "remediated" | where ResultType in (0) | where AppDisplayName <> "Microsoft Authentication Broker" | project TimeGenerated,ResultType, ResultDescription,AppDisplayName, UserPrincipalName,UserType, RiskLevelAggregated, RiskLevelDuringSignIn, RiskState, RiskDetail, RiskEventTypes_V2, ConditionalAccessStatus, AuthenticationRequirement,AADTenantId,ResourceTenantId