// Source: https://github.com/SlimKQL/Hunting-Queries-Detection-Rules
// Collected: 2026-08-09
// KQL Library - https://github.com/sivolko/kql-library

let DriverwithLowPrevalence =
DeviceFileEvents
| where ActionType == "FileCreated"
| where FileName endswith ".sys"
| invoke FileProfile(SHA1,10000)
| where GlobalPrevalence <= 150
| invoke FileProfile(SHA1,1000)
| where GlobalPrevalence <= 150 or isempty(GlobalPrevalence)
| join kind=leftouter DeviceFileCertificateInfo on SHA1
| project FileName;
let DevicewithLPDriverActivated =
DeviceEvents
// Event ID 3004 — Kernel-mode Driver Validation
//| where ReportId == "3004"
| where ActionType == @"DriverLoad"
| where FileName has_any(DriverwithLowPrevalence)
| distinct DeviceName;
DeviceEvents
//| where ReportId == "5013"
| where ActionType == @"TamperingAttempt"
| where DeviceName has_any(DevicewithLPDriverActivated)


// MITRE ATT&CK Mapping

// File Creation and Prevalence Check:
// Tactic: Defense Evasion
// Technique: T1036.005 - Masquerading: Match Legitimate Name or Location
// Description: The query identifies newly created .sys files (drivers) and checks their global prevalence to detect potentially rare or suspicious drivers.

// Driver Load Event:
// Tactic: Execution
// Technique: T1547.001 - Boot or Logon Autostart Execution: Registry Run Keys / Startup Folder
// Description: The query monitors for driver load events (Event ID 3004) to detect the activation of low-prevalence drivers, which could indicate malicious activity.

// Tampering Attempt Detection:
// Tactic: Defense Evasion
// Technique: T1562.001 - Impair Defenses: Disable or Modify Tools
// Description: The query looks for tampering attempts (Event ID 5013) on devices where low-prevalence drivers have been activated, indicating potential attempts to disable security tools or modify system