// Source: https://github.com/microsoft/AzureMonitorCommunity
// Collected: 2026-07-13
// KQL Library - https://github.com/sivolko/kql-library

AzureActivity
| extend subId =  split(_ResourceId,"/").[2]
| extend resGr =  split(_ResourceId,"/").[4]
| project _ResourceId, subId, resGr

AzureActivity
| parse _ResourceId with * '/subscriptions/' subId '/' *
| parse _ResourceId with * '/resourcegroups/' resGr '/' *
| distinct  subId, resGr

AzureActivity
| extend subId = extract(@"/subscriptions/(.*?)/", 1,_ResourceId)
| extend resGr = extract(@"/resourcegroups/(.*?)/", 1,_ResourceId)
| project subId, resGr


// Just do a regex lookup  
AzureActivity
| where _ResourceId matches regex @"/subscriptions/(.*?)/"