// Source: https://github.com/letisiapangataa/azure-sentinel-power-bi-dashboard
// Collected: 2026-05-25
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where EventID == 4688  // Process creation
| where Process contains "powershell.exe"
| where CommandLine contains "-enc" or CommandLine contains "-nop" or CommandLine contains "downloadstring"
| summarize SuspiciousCommands = count() by Computer, Account, bin(TimeGenerated, 1h)
| order by TimeGenerated desc