// Source: https://github.com/sivolko/kql-library
// Collected: 2026-07-21
// KQL Library - https://github.com/sivolko/kql-library

let MonitoredCommands = dynamic(["ie4uinit","ie4uinit.exe"]);
DeviceEvents
| where Timestamp > ago(1hr)
| where ActionType == "ShellLinkCreateFileEvent"
| where tostring(AdditionalFields) contains "ShellLink"
| where parse_json(AdditionalFields)["ShellLinkShowCommand"] != 'SW_SHOWNORMAL'
| extend ShellLinkCommandLine = parse_json(AdditionalFields)["ShellLinkCommandLine"]
| extend ShellLinkIconPath = parse_json(AdditionalFields)["ShellLinkIconPath"]
| where ShellLinkCommandLine != ""
| where ShellLinkCommandLine has_any (MonitoredCommands)