// Source: https://github.com/microsoft/AzureMonitorCommunity
// Collected: 2026-07-03
// KQL Library - https://github.com/sivolko/kql-library

union Event, Syslog // Event table stores Windows event records, Syslog stores Linux records
| where TimeGenerated > ago(1h)
| where EventLevelName == "Error" // EventLevelName is used in the Event (Windows) records
or SeverityLevel== "err" // SeverityLevel is used in Syslog (Linux) records