// Source: https://github.com/THESunnyNguyen/kql-hunting-queries
// Collected: 2026-07-07
// KQL Library - https://github.com/sivolko/kql-library

let lookback = 14d;
let businessHourStart = 7;
let businessHourEnd = 18;
AuditLogs
| where TimeGenerated >= ago(lookback)
| where OperationName has_any ("Add member to role", "Add eligible member to role", "Add scoped member to role")
| extend HourOfDay = datetime_part("hour", TimeGenerated)
| extend DayName = format_datetime(TimeGenerated, "dddd")
| where HourOfDay < businessHourStart or HourOfDay >= businessHourEnd or DayName in ("Saturday", "Sunday")
| extend InitiatedByUser = tostring(InitiatedBy.user.userPrincipalName)
| extend InitiatedByApp = tostring(InitiatedBy.app.displayName)
| project TimeGenerated, OperationName, Result, InitiatedByUser, InitiatedByApp, TargetResources, HourOfDay, DayName, CorrelationId
| order by TimeGenerated desc
