// Source: https://github.com/kehaitcfyn/DefenderXDR
// Collected: 2026-07-20
// KQL Library - https://github.com/sivolko/kql-library

IdentityLogonEvents
| where Protocol == @"Kerberos"
| extend ParsedFields=parse_json(AdditionalFields)
| project Timestamp, ActionType, DeviceName, IPAddress, DestinationDeviceName, AccountName, AccountDomain, EncryptionType = tostring(ParsedFields.EncryptionType)
| where EncryptionType == @"Rc4Hmac"