// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-08-14
// KQL Library - https://github.com/sivolko/kql-library

SigninLogs
| where TimeGenerated > ago (90d)
| where ResultType == "500121"
| mv-expand todynamic(AuthenticationDetails)
| project AuthenticationDetails, ResultType
| extend ['MFA Failure Type'] = tostring(parse_json(AuthenticationDetails).authenticationStepResultDetail)
| where ['MFA Failure Type'] startswith "MFA denied"
| summarize Count=count()by ['MFA Failure Type']
| sort by Count