// Source: https://github.com/ugurkocde/kql_search_submissions
// Collected: 2026-06-11
// KQL Library - https://github.com/sivolko/kql-library

SigninLogs
| where TimeGenerated > ago(1h)
| where ResultDescription == "Sign-in was blocked because it came from an IP address with malicious activity"
| extend ["Password Result Detail"] = tostring(parse_json(AuthenticationDetails)[0].authenticationStepResultDetail), ["MFA Result Detail"] = tostring(parse_json(AuthenticationDetails)[1].authenticationStepResultDetail)
| where ['Password Result Detail']  has_any ("Correct password", "First factor requirement satisfied by claim in the token")
| project
    TimeGenerated,
    UserPrincipalName,
    UserDisplayName,
    IPAddress,
    Location,
    ResultType,
    ResultDescription,
    AppDisplayName,
    ['Password Result Detail'],
    ['MFA Result Detail'],
    UserAgent 