// Source: https://github.com/obsida-uk/Azure-BlueTeam-Toolkit
// Collected: 2026-05-21
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where ActionType == "PowerShellCommand"
| where InitiatingProcessFileName == "powershell.exe"
| where InitiatingProcessAccountName != "system"
| where AdditionalFields.Command == "Set-ExecutionPolicy"
| project TimeGenerated, DeviceName, InitiatingProcessAccountName