// Source: https://github.com/ge0mant1s/SOaC-Enterprise
// Collected: 2026-06-28
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent | where EventID == 4624 | where LogonType in (3, 10) | where Account startswith "EXCHANGESERVER" or Account contains "ExchSvc" | where IpAddress != "-" | join kind=inner (SecurityEvent | where EventID == 4648 | where TargetServerName != Computer) on Computer | where TimeGenerated > ago(2h) | summarize count() by Account, IpAddress, TargetServerName