// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-10-02
// KQL Library - https://github.com/sivolko/kql-library

AuditLogs
| where TimeGenerated > ago(90d)
| where OperationName == "Add group"
| where parse_json(tostring(TargetResources[0].modifiedProperties))[1].displayName == "IsAssignableToRole"
| where parse_json(tostring(parse_json(tostring(TargetResources[0].modifiedProperties))[1].newValue))[0] == true
| extend GroupName = tostring(parse_json(tostring(parse_json(tostring(TargetResources[0].modifiedProperties))[0].newValue))[0])
| extend Actor = tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)
| extend ['Actor IP Address'] = tostring(parse_json(tostring(InitiatedBy.user)).ipAddress)
| project TimeGenerated, OperationName, GroupName, Actor, ['Actor IP Address']