// Source: https://github.com/EmreOzanMemis/AzureSentinel
// Collected: 2026-05-24
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent
| where TimeGenerated > ago (1d)
| summarize ['Last Record Received']  = datetime_diff("minute", now(), max(TimeGenerated)) by Computer
| project Computer, ['Last Record Received']
| where ['Last Record Received'] >= 60
| order by ['Last Record Received'] desc 