// Source: https://github.com/LaurieRhodes/kustainer-ui
// Collected: 2026-06-28
// KQL Library - https://github.com/sivolko/kql-library

.create-merge table AuditLogsRaw (records:dynamic)

.create-or-alter table AuditLogsRaw ingestion json mapping 'AuditLogsRawMapping' '[{"column":"records","Properties":{"path":"$.records"}}]'

.create-merge table AuditLogs(
TenantId:string,
SourceSystem:string,
TimeGenerated:datetime,
ResourceId:string,
OperationName:string,
OperationVersion:string,
Category:string,
ResultType:string,
ResultSignature:string,
ResultDescription:string,
DurationMs:long,
CorrelationId:string,
Resource:string,
ResourceGroup:string,
ResourceProvider:string,
Identity:string,
Level:string,
Location:string,
AdditionalDetails:dynamic,
Id:string,
InitiatedBy:dynamic,
LoggedByService:string,
Result:string,
ResultReason:string,
TargetResources:dynamic,
AADTenantId:string,
ActivityDisplayName:string,
ActivityDateTime:datetime,
AADOperationType:string,
Type:string,
['_ItemId']:string,
['_ResourceId']:string,
['_SubscriptionId']:string,
['_TimeReceived']:datetime)

.create-or-alter function AuditLogsExpand {
AuditLogsRaw
//| extend events = records
| mv-expand events = records
| project
TenantId=tostring(events.tenantId),
SourceSystem=tostring(''),
TimeGenerated=todatetime(events.['time']),
ResourceId=tostring(events.resourceId),
OperationName=tostring(events.operationName),
OperationVersion=tostring(events.operationVersion),
Category=tostring(events.category),
ResultType=tostring(events.properties.resultType),
ResultSignature=tostring(events.resultSignature),
ResultDescription=tostring(events.resultDescription),
DurationMs=tolong(events.durationMs),
CorrelationId=tostring(events.correlationId),
Resource=tostring(''),
ResourceGroup=tostring(''),
ResourceProvider=tostring(''),
Identity=tostring(events.identity),
Level=tostring(events.Level),
Location=tostring(''),
AdditionalDetails=todynamic(events.properties.additionalDetails),
Id=tostring(events.properties.id),
InitiatedBy=todynamic(events.properties.initiatedBy),
LoggedByService=tostring(events.properties.loggedByService),
Result=tostring(events.properties.result),
ResultReason=tostring(events.properties.resultReason),
TargetResources=todynamic(events.properties.targetResources),
AADTenantId=tostring(events.properties.tenantId),
ActivityDisplayName=tostring(events.properties.activityDisplayName),
ActivityDateTime=todatetime(events.properties.activityDateTime),
AADOperationType=tostring(events.properties.operationType),
Type=tostring('AuditLogs'),
_ItemId=tostring(''),
_ResourceId=tostring(events.resourceId),
_SubscriptionId=tostring(''),
_TimeReceived=todatetime(now())}

.alter table AuditLogs policy update @'[{"Source": "AuditLogsRaw", "Query": "AuditLogsExpand()", "IsEnabled": "False", "IsTransactional": true}]'

.alter table AuditLogs policy update @'[{"Source": "AuditLogsRaw", "Query": "AuditLogsExpand()", "IsEnabled": "True", "IsTransactional": true}]'

