// Source: https://github.com/CraigCloudITPro/Microsoft-Sentinel
// Collected: 2026-05-29
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where ActionType == "BrowserScriptExecution"
| where AdditionalFields contains "ActiveXObject"
| extend InitiatingProcessDetails = strcat(InitiatingProcessFileName, " | ", InitiatingProcessCommandLine)
| extend RemoteSessionDetails = iif(IsInitiatingProcessRemoteSession == true, strcat(InitiatingProcessRemoteSessionDeviceName, " | ", InitiatingProcessRemoteSessionIP), "No Remote Session")
| project TimeGenerated, DeviceName, AccountName, AccountDomain, InitiatingProcessDetails, RemoteSessionDetails, AdditionalFields
| order by TimeGenerated desc