// Source: https://github.com/chadmcox/Sentinel-and-Defender-Queries
// Collected: 2026-07-07
// KQL Library - https://github.com/sivolko/kql-library

let FailureThreshold = 15;
IdentityLogonEvents
| where Timestamp >= ago(7d)
| where ActionType in ("LogonFailed", "InvalidPassword")
| summarize
    FailedLogons = count(),
    SrcIPs = dcount(IPAddress),
    FirstSeen = min(Timestamp),
    LastSeen = max(Timestamp)
    by AccountName, AccountDomain
| where FailedLogons >= FailureThreshold and SrcIPs >= 3
| sort by FailedLogons desc