// Source: https://github.com/Azure/ausgovcaf-cloudsoe
// Collected: 2026-06-05
// KQL Library - https://github.com/sivolko/kql-library

SecurityEvent 
| where EventID == 4650 or EventID == 4651
| extend ed = parse_xml(EventData).EventData.Data
| mv-apply ed on 
(
    where ed['@Name'] == 'MMLifetime'
    | project LifetimeSeconds = (ed['#text'] * 60)
)
| where LifetimeSeconds >= 14400
| project TimeGenerated, Computer, Activity, LifetimeSeconds