// Source: https://github.com/reprise99/Sentinel-Queries
// Collected: 2026-07-03
// KQL Library - https://github.com/sivolko/kql-library

SigninLogs
| where TimeGenerated > ago(7d)
| where ResultType == 0
| where isnotempty(Location)
| summarize
    ['Count of countries']=dcount(Location),
    ['List of countries']=make_set(Location)
    by UserPrincipalName, bin(TimeGenerated, 1d)
| where ['Count of countries'] >= 3

//Advanced Hunting query

//Data connector required for this query - Advanced Hunting with Azure AD P2 License

AADSignInEventsBeta
| where Timestamp > ago(7d)
| where ErrorCode == 0
| where isnotempty(Country)
| summarize
    ['Count of countries']=dcount(Country),
    ['List of countries']=make_set(Country)
    by AccountUpn, bin(Timestamp, 1d)
| where ['Count of countries'] >= 3