// Source: https://github.com/SlimKQL/Hunting-Queries-Detection-Rules
// Collected: 2026-07-26
// KQL Library - https://github.com/sivolko/kql-library

let QueryPeriod = 30d;
let DetectionPeriod = 1h;
let HyperVEnabledEndpoint =
DeviceProcessEvents
| where Timestamp > ago(QueryPeriod)
| where FileName == "WindowsSandboxServer.exe"
| distinct DeviceId;
let VulnerableEndpoint =
DeviceTvmSoftwareVulnerabilities
| where CveId == "CVE-2025-21333"
| distinct DeviceId;
let NewExePOCCreation =
DeviceFileEvents
| where Timestamp > ago(DetectionPeriod)
| where ActionType == "FileCreated"
| where FileName endswith ".exe"
| distinct FileName;
DeviceEvents
| where Timestamp > ago(DetectionPeriod)
| where ActionType == "ProcessPrimaryTokenModified"
| where FileName has_any(NewExePOCCreation)
| where DeviceId has_any(HyperVEnabledEndpoint) and DeviceId has_any(VulnerableEndpoint)
