// Source: https://github.com/RachelBulmerSec/Cloud-Security-Engineering-Portfolio
// Collected: 2026-05-20
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where ActionType in ("ControlledFolderAccessViolationAudited", "ControlledFolderAccessViolationBlocked")
| project Timestamp,
          DeviceName,
          FileName,
          FolderPath,
          InitiatingProcessFileName,
          InitiatingProcessCommandLine,
          InitiatingAccount = InitiatingProcessAccountName
| sort by Timestamp desc