// Source: https://github.com/kehaitcfyn/DefenderXDR
// Collected: 2026-06-20
// KQL Library - https://github.com/sivolko/kql-library

DeviceEvents
| where Timestamp > ago(30d)
| where ActionType == @"FirewallInboundConnectionBlocked"
| summarize TargetDevice=dcount(DeviceName), TargetPort=dcount(LocalPort) by RemoteIP
| where TargetDevice > 20
| where TargetPort > 10
| sort by TargetDevice, TargetPort desc 