// Source: https://github.com/dabbychiu/Purple-Team-Detection-Lab
// Collected: 2026-08-29
// KQL Library - https://github.com/sivolko/kql-library

let ASReqs = SecurityEvent
    | where EventID == 4768
    | extend TargetUser = extract(@'Name="TargetUserName">([^<]+)<', 1, EventData)
    | extend SrcIp = extract(@'Name="IpAddress">([^<]+)<', 1, EventData)
    | where TimeGenerated > ago(2h)
    | project ASTime=TimeGenerated, TargetUser, SrcIp;
SecurityEvent
| where EventID == 4769
| where TimeGenerated > ago(2h)
| extend TargetUser = extract(@'<Data Name="TargetUserName">([^<]+)</Data>', 1, tostring(EventData))
| extend ServiceName = extract(@'<Data Name="ServiceName">([^<]+)</Data>', 1, tostring(EventData))
| extend SrcIp = extract(@'<Data Name="IpAddress">([^<]+)</Data>', 1, tostring(EventData))
| where ServiceName !startswith "krbtgt"
| join kind=leftanti ASReqs on $left.TargetUser == $right.TargetUser
| summarize TgsCount=count(), Services=make_set(ServiceName, 20)
    by TargetUser, SrcIp, bin(TimeGenerated, 1h)
| where TgsCount >= 1
| order by TimeGenerated desc