// Source: https://github.com/davidalonsod/Dalonso-Security-Repo
// Collected: 2026-05-19
// KQL Library - https://github.com/sivolko/kql-library

let NSGOps = dynamic([
    "MICROSOFT.NETWORK/NETWORKSECURITYGROUPS/DELETE",
    "MICROSOFT.NETWORK/NETWORKSECURITYGROUPS/WRITE",
    "MICROSOFT.NETWORK/NETWORKSECURITYGROUPS/SECURITYRULES/WRITE",
    "MICROSOFT.NETWORK/NETWORKSECURITYGROUPS/SECURITYRULES/DELETE"
]);
AzureActivity
| where TimeGenerated > ago(30d)
| where OperationNameValue has_any (NSGOps)
| where ActivityStatusValue =~ "Success"
| extend ChangeType = case(
    OperationNameValue has "DELETE" and OperationNameValue has "NETWORKSECURITYGROUPS/DELETE", "NSG Deleted",
    OperationNameValue has "SECURITYRULES/DELETE", "Security Rule Deleted",
    OperationNameValue has "SECURITYRULES/WRITE",  "Security Rule Modified/Added",
    OperationNameValue has "NETWORKSECURITYGROUPS/WRITE", "NSG Created/Modified",
    "Other")
| project
    TimeGenerated,
    Caller,
    CallerIpAddress,
    ChangeType,
    ResourceId,
    ResourceGroup,
    SubscriptionId,
    Properties
| order by TimeGenerated desc