// Source: https://github.com/petitess/kusto
// Collected: 2026-06-07
// KQL Library - https://github.com/sivolko/kql-library

let starttime = 5d;
let timeframe = 30m;
let Computers=Syslog
    | where TimeGenerated >= ago(starttime)
    | summarize EventCount=count() by Computer, bin(TimeGenerated, timeframe)
    | where EventCount > 1500
    | order by TimeGenerated
    | summarize EventCount=make_list(EventCount), TimeGenerated=make_list(TimeGenerated) by Computer
    | extend outliers=series_decompose_anomalies(EventCount, 2)
    | mv-expand TimeGenerated, EventCount, outliers
    | where outliers == 1
    | distinct Computer
;
Syslog
| where TimeGenerated >= ago(starttime)
| where Computer in (Computers)
| summarize EventCount=count() by Computer, bin(TimeGenerated, timeframe)
| render timechart 